package ModelItems

type MStockItem struct {
	SharedBookStoreCode         string `sql:"shared_book_store_code"`
	ShopCode                    string `sql:"shop_code"`
	ShopName                    string `sql:"shop_name"`
	JanCode                     string `sql:"jan_code"`
	ProductName                 string `sql:"product_name"`
	MakerName                   string `sql:"maker_name"`
	ListPrice                   int64  `sql:"list_price"`
	StockQuantity               int64  `sql:"stock_quantity"`
	CumulativeReceivingQuantity int64  `sql:"cumulative_receiving_quantity"`
	CumulativeSalesQuantity     int64  `sql:"cumulative_sales_quantity"`
	FirstSalesDate              string `sql:"first_sales_date"`
	TotalRecords                int64  `sql:"total_records"`
	MagazineName                string `sql:"magazine_name"`
	JanSeqNumber                int64  `sql:"jan_seq_number"`
	MonthNum                    int64  `sql:"month_num"`
	AuthorName                  string `sql:"author_name"`
	LastSalesDate               string `sql:"last_sales_date"`
	SellingDate                 string `sql:"selling_date"`
	SalesQuantityDay1           int64  `sql:"sales_quantity_day1"`
	SalesQuantityDay2           int64  `sql:"sales_quantity_day2"`
	SalesQuantityDay3           int64  `sql:"sales_quantity_day3"`
	SalesQuantityDay4           int64  `sql:"sales_quantity_day4"`
	SalesQuantityDay5           int64  `sql:"sales_quantity_day5"`
	SalesQuantityDay6           int64  `sql:"sales_quantity_day6"`
	SalesQuantityDay7           int64  `sql:"sales_quantity_day7"`
	SalesQuantityDay8           int64  `sql:"sales_quantity_day8"`
	SalesQuantityDay9           int64  `sql:"sales_quantity_day9"`
	SalesQuantityDay10          int64  `sql:"sales_quantity_day10"`
	SalesQuantityDay11          int64  `sql:"sales_quantity_day11"`
	SalesQuantityDay12          int64  `sql:"sales_quantity_day12"`
	SalesQuantityDay13          int64  `sql:"sales_quantity_day13"`
	SalesQuantityDay14          int64  `sql:"sales_quantity_day14"`
	SalesQuantityDay15          int64  `sql:"sales_quantity_day15"`
	SalesQuantityDay16          int64  `sql:"sales_quantity_day16"`
	SalesQuantityDay17          int64  `sql:"sales_quantity_day17"`
	SalesQuantityDay18          int64  `sql:"sales_quantity_day18"`
	SalesQuantityDay19          int64  `sql:"sales_quantity_day19"`
	SalesQuantityDay20          int64  `sql:"sales_quantity_day20"`
	SalesQuantityDay21          int64  `sql:"sales_quantity_day21"`
	SalesQuantityDay22          int64  `sql:"sales_quantity_day22"`
	SalesQuantityDay23          int64  `sql:"sales_quantity_day23"`
	SalesQuantityDay24          int64  `sql:"sales_quantity_day24"`
	SalesQuantityDay25          int64  `sql:"sales_quantity_day25"`
	SalesQuantityDay26          int64  `sql:"sales_quantity_day26"`
	SalesQuantityDay27          int64  `sql:"sales_quantity_day27"`
	SalesQuantityDay28          int64  `sql:"sales_quantity_day28"`
	SalesQuantityDay29          int64  `sql:"sales_quantity_day29"`
	SalesQuantityDay30          int64  `sql:"sales_quantity_day30"`
	SalesQuantityDay31          int64  `sql:"sales_quantity_day31"`
	SalesQuantityDay32          int64  `sql:"sales_quantity_day32"`
	SalesQuantityDay33          int64  `sql:"sales_quantity_day33"`
	SalesQuantityDay34          int64  `sql:"sales_quantity_day34"`
	SalesQuantityDay35          int64  `sql:"sales_quantity_day35"`
	SalesQuantityDay36          int64  `sql:"sales_quantity_day36"`
	SalesQuantityDay37          int64  `sql:"sales_quantity_day37"`
	SalesQuantityDay38          int64  `sql:"sales_quantity_day38"`
	SalesQuantityDay39          int64  `sql:"sales_quantity_day39"`
	SalesQuantityDay40          int64  `sql:"sales_quantity_day40"`
}
