package WebApp

const (
	APP_VERSION                = "WebPOSCloud dev 201704"
	DEFAULT_LOGO_FILE          = "default_logo.png"
	DEFAULT_BQ_DATASET         = "ba"
	DEFAULT_ST_TRANSFER_DIR    = "wp_cloud/wp_gce_to_bq_transfer"
	DEFAULT_LOCAL_TRANSFER_DIR = "tmp/transfer"

	CONFIG_KEY_APP_WEBSITE_TITLE  = "App.WebSiteTitle"
	CONFIG_KEY_GCP_KEY_FILE       = "BQ.KeyFile"
	CONFIG_KEY_GCP_MAIL_ACCOUNT   = "BQ.MailAccount"
	CONFIG_KEY_GCP_PROJECT_ID     = "BQ.ProjectId"
	CONFIG_KEY_BQ_DATASET         = "BQ.Dataset"
	CONFIG_KEY_ST_TRANSFER_DIR    = "ST.TransferDir"
	CONFIG_KEY_LOCAL_TRANSFER_DIR = "Local.TransferDir"
	CONFIG_KEY_SESSION_TIMEOUT    = "Server.SessionTimeout"
	CONFIG_KEY_PW_EXPIRING_DATE   = "Server.PwExpiringDate"
	CONFIG_KEY_APP_STATIC_DIR     = "App.staticDir"
	CFG_KEY_SESSION_STORE_DIR     = "Server.SessionStoreDir"

	//CONFIG_KEY_SERVER_ENABLE_HTTP         = "Server.EnableHttp"
	//CONFIG_KEY_SERVER_ADDR                = "Server.Addr"
	//CONFIG_KEY_SERVER_READ_TIMEOUT        = "Server.ReadTimeout"
	//CONFIG_KEY_SERVER_WRITE_TIMEOUT       = "Server.WriteTimeout"
	//CONFIG_KEY_SERVER_MAX_HEADER_BYTES    = "Server.MaxHeaderBytes"
	//CONFIG_KEY_SERVER_STATIC_DIR          = "Server.StaticDir"
	//CONFIG_KEY_SERVER_STATIC_WEB_PATH     = "Server.StaticWebPath"
	//CONFIG_KEY_SERVER_VIEW_DIR            = "Server.ViewDir"
	//CONFIG_KEY_SERVER_SESSION_STORE_DIR   = "Server.SessionStoreDir"
	//CONFIG_KEY_SERVER_COOKIE_SECRET       = "Server.CookieSecret"
	CONFIG_KEY_SERVER_CACHE_STORE_DIR = "Server.CacheStoreDir"
	//CONFIG_KEY_SERVER_ENABLE_GZIP         = "Server.EnableGzip"
	//CONFIG_KEY_SERVER_ENABLE_HTTP2        = "Server.EnableHttp2"
	//CONFIG_KEY_SERVER_FORCE_HTTPS         = "Server.ForceHttps"
	//CONFIG_KEY_SERVER_ENABLE_CSRF_PROTECT = "Server.EnableCsrfProtect"
	//CONFIG_KEY_SERVER_ENABLE_HTTPS        = "Server.EnableHttps"
	//CONFIG_KEY_SERVER_ADDR_HTTPS          = "Server.AddrHttps"
	//CONFIG_KEY_SERVER_CERT_FILE           = "Server.CertFile"
	//CONFIG_KEY_SERVER_KEY_FILE            = "Server.KeyFile"
	CONFIG_KEY_SERVER_LOG_LEVEL = "Server.LogLevel"
	//CONFIG_KEY_DATABASE_DRIVER = "Database.Driver"
	//CONFIG_KEY_DATABASE_HOST   = "Database.Host"
	//CONFIG_KEY_DATABASE_SERVER = "Database.Server"
	//CONFIG_KEY_DATABASE_PORT   = "Database.Port"
	//CONFIG_KEY_DATABASE_USER   = "Database.User"
	//CONFIG_KEY_DATABASE_PWD    = "Database.Pwd"
	//CONFIG_KEY_DATABASE_DBNAME = "Database.DatabaseName"
	CONFIG_PATH_FILE_SHOP_LIST_DOWNLOAD = "Download.ShopList"
	CONFIG_ACCESS_KEY_HONTO_API         = "Honto.AccessKey"
	CONFIG_RETRY_COUNT                  = "BQ.APIRetryCount"
	CONFIG_TIME_RETRY                   = "BQ.APITimeRetry"
	CONFIG_LIST_CODE_HTTP               = "BQ.APICodeHTTP"
	CONFIG_SEARCH_GOODS_URL             = "Honto.URL"

	CONFIG_DOWNLOAD_RECORD_LIMIT_FROM = "Download.RecordLimitFrom"
	CONFIG_DOWNLOAD_RECORD_LIMIT_TO   = "Download.RecordLimitTo"

	CONSTANT_URL_HTTP = "http"
)
